collections:
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.nxos
  - name: cisco.aci
  - name: netapp.elementsw
  - name: netapp.um_info
  - name: netapp.storagegrid
  - name: netapp.ontap
  - name: paloaltonetworks.panos
  - name: servicenow.itsm
  - name: community.vmware
  - name: vmware.vmware_rest
  - name: f5networks.f5_modules
  - name: awx.awx
#  - name: ansible.tower
  - name: ansible.controller
  - name: redhat_cop.controller_configuration
