---
collections:
  #- name: awx.awx
  #- name: ansible.tower
  #- name: ansible.controller
  #- name: redhat_cop.controller_configuration
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.nxos
  - name: cisco.aci
